-- liquibase formatted sql

-- changeset hakan-aslim:creating-initial-tables-1
CREATE TABLE AUTHOR
(
    ID            VARCHAR(36)       NOT NULL,
    FULL_NAME     VARCHAR(255)      NOT NULL,
    CREATED_BY    VARCHAR(36)       NOT NULL,
    CREATE_DATE   TIMESTAMP         WITH TIME ZONE NOT NULL,
    MODIFIED_BY   VARCHAR(36),
    MODIFIED_DATE TIMESTAMP         WITH TIME ZONE,
    CONSTRAINT AUTHOR_PKEY PRIMARY KEY (ID)
);

-- changeset hakan-aslim:creating-initial-tables-2
CREATE TABLE RECIPE
(
    ID            VARCHAR(36)       NOT NULL,
    NAME          VARCHAR(100)      NOT NULL,
    DESCRIPTION   VARCHAR(255)      NOT NULL,
    SERVANT       VARCHAR(60)       NOT NULL,
    COURSE        VARCHAR(30)       NOT NULL,
    SPECIAL_DIET  VARCHAR(30)       NOT NULL,
    CREATED_BY    VARCHAR(36)       NOT NULL,
    CREATE_DATE   TIMESTAMP         WITH TIME ZONE NOT NULL,
    MODIFIED_BY   VARCHAR(36),
    MODIFIED_DATE TIMESTAMP         WITH TIME ZONE,
    CONSTRAINT RECIPE_PKEY PRIMARY KEY (ID)
);

-- changeset hakan-aslim:creating-initial-tables-3
CREATE TABLE RECIPE_INGREDIENT
(
    ID            VARCHAR(36)       NOT NULL,
    RECIPE_ID     VARCHAR(36)       NOT NULL,
    TEXT          VARCHAR(255)      NOT NULL,
    CONSTRAINT RECIPE_INGREDIENT_PKEY PRIMARY KEY (ID)
);

ALTER TABLE RECIPE_INGREDIENT
    ADD CONSTRAINT FK_RECIPE_ING_RECIPE
        FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID);

-- changeset hakan-aslim:creating-initial-tables-4
CREATE TABLE RECIPE_INSTRUCTION
(
    ID            VARCHAR(36)       NOT NULL,
    RECIPE_ID     VARCHAR(36)       NOT NULL,
    TEXT          VARCHAR(255)      NOT NULL,
    CONSTRAINT RECIPE_INST_PKEY PRIMARY KEY (ID)
);
ALTER TABLE RECIPE_INSTRUCTION
    ADD CONSTRAINT FK_RECIPE_INST_RECIPE
        FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID);

